import type { Metadata } from "next";
import * as Fonts from "@root/app/lib/fonts";
import "./globals.css";
import ChangeThemeButton from "@root/components/ChangeThemeButton";
import { ThemeScript } from "./lib/theme.provider";
import { getInitialTheme } from "./lib/theme.server";
import Providers from "@root/components/Providers";
import styles from "./layout.module.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: {
    width: "device-width",
    height: "device-height",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialTheme = await getInitialTheme();

  return (
    <Providers theme={initialTheme}>
        <ThemeScript/>
        <html lang="en" className={`${Fonts.hankenGrotesk.variable} ${Fonts.LibreBaskerville.variable} ${Fonts.recursive.variable}`}>
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <body>
            <main className={styles.root}>
              <header className={styles.header}>
                <div className={styles.headerContent}>
                  <ChangeThemeButton />
                </div>
              </header>

              <div className={styles.content}>
                {children}
              </div>

              <footer className={styles.footer}>
                <div className={styles.footerContent}>
                  <small>2026 © Max Lair</small>
                </div>
              </footer>
            </main>
          </body>
        </html>
    </Providers>
  );
}
