import type { Metadata } from "next";
import * as Fonts from "@root/app/lib/fonts";
import "./globals.css";
import ChangeThemeButton from "@root/components/ChangeThemeButton";
import { ThemeScript } from "./lib/theme.provider";
import { getInitialTheme } from "./lib/theme.server";
import Providers from "@root/components/Providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialTheme = await getInitialTheme();

  return (
    <Providers theme={initialTheme}>
        <ThemeScript/>
        <html lang="en" className={`${Fonts.hankenGrotesk.variable} ${Fonts.LibreBaskerville.variable}`}>
            {/* replace w Button later */}
          <body>{children}</body>
        </html>
    </Providers>
  );
}
